### ISSUE TITLE
设备断言问题

### ISSUE THREAD

**Issue by ShunZuo-AI** [ZhenZHAO/AugSeg#33]
Traceback (most recent call last):
  File "./train_semi.py", line 591, in <module>
    main(args)
  File "./train_semi.py", line 183, in main
    cfg
  File "./train_semi.py", line 380, in train
    logits_u_aug.detach(), thresh=p_threshold)
  File "/fs1/private/user/zuoshun/project/AugSeg/augseg/utils/loss_helper.py", line 313, in compute_unsupervised_loss_by_threshold
    target[~thresh_mask] = 255
RuntimeError: CUDA error: device-side assert triggered
作者你好，我配置环境后，运行代码出现此问题了，请问你有遇到过吗？

**Comment by ZhenZHAO** [comment]
没有。。。这代码应该很好跑才对呀。。你试试加上CUDA_LAUNCH_BLOCKING=1，看看输出啥，调调

**Comment by ShunZuo-AI** [comment]
感谢您能够回复我的issue！最近拜读的您文章，反复阅读了一周，每次阅读都能有新的体会，可视为论文教材。祝愿您的科研工作越来越好。再次感谢！！
